[request_definition]
r = user, org, project, module, action

[policy_definition]
p = role, domain, module, action

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.user, p.role, r.org) && r.org == p.domain && r.module == p.module && r.action == p.action) || \
    (g(r.user, p.role, r.project) && r.project == p.domain && r.module == p.module && r.action == p.action)