"""Added created_by in project and project_milestone

Revision ID: 543ebf4bc47f
Revises: cd5f4a377ce3
Create Date: 2026-07-02 14:44:08.098448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543ebf4bc47f'
down_revision: Union[str, Sequence[str], None] = 'cd5f4a377ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    op.add_column('project_milestones', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.alter_column('project_milestones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_milestones', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_project_milestones_created_by'), 'project_milestones', ['created_by'], unique=False)
    op.create_foreign_key(None, 'project_milestones', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_column('projects', 'created_by')
    op.drop_constraint(None, 'project_milestones', type_='foreignkey')
    op.drop_index(op.f('ix_project_milestones_created_by'), table_name='project_milestones')
    op.alter_column('project_milestones', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_milestones', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('project_milestones', 'created_by')
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('casbin_rule_pkey'))
    )
    # ### end Alembic commands ###
